### ISSUE TITLE
Event feature test fails randomly

### ISSUE THREAD

**Issue by Blaidd-Drwg** [hpi-swt2/workshop-portal#374]
'Event application letters overview on event page logged in as Organizer I can filter displayed application letters by their status and simultaneously sort them' sometimes fails with the message 'expected #<Capybara::Session> to contain ordered "Karl100 Doe100", "Karl101 Doe101", "Karl102 Doe102", "Karl98 Doe98", and "Karl99 Doe99"' at [this line](https://github.com/hpi-swt2/workshop-portal/blob/5e12a7d041a4019d84bd2d75b3b043fac7931716/spec/features/events_spec.rb#L299).

From what I've gathered so far, the names are sorted by id in the HTML (...Karl99, Karl100...), yet the test expects them to be sorted alphabetically (...Karl100, Karl99...).

**Comment by Blaidd-Drwg** [comment]
[`contain_ordered`](https://github.com/hpi-swt2/workshop-portal/blob/5e12a7d041a4019d84bd2d75b3b043fac7931716/spec/support/matchers/ordered_appearance.rb) does not fail consistently, sometimes (seemingly at random) it passes even though it shouldn't. @MasterCarl Any idea why?

**Comment by MasterCarl** [comment]
That's odd, I've never had these tests fail. Honestly, I have no idea. Does this only happen locally?

**Comment by Blaidd-Drwg** [comment]
No, on Travis as well. See #371: continuous-integration/travis-ci/push and continuous-integration/travis-ci/pr both failed at first. I restarted continuous-integration/travis-ci/pr without any changes to the branch and suddenly it passed.

As far as I can see, the problems are two:
1) In the test, names are **never** sorted alphabetically, which should cause it to fail every time.
2) In same cases, though, `contain_ordered` still passes, which is why our build status on dev is currently green.

**Comment by tom95** [comment]
Could you provide a link to the travis build in question? I had this happen too, but I thought I fixed it on dev.

**Comment by Blaidd-Drwg** [comment]
The one that failed: https://travis-ci.org/hpi-swt2/workshop-portal/builds/193932385
The one that succeeded later on: https://travis-ci.org/hpi-swt2/workshop-portal/builds/193932389

I haven't merged your commits into that branch, so the builds don't include your fix. But since I'm having the exact same problem when testing the current dev locally, I figure it's still an issue on Travis as well.

**Comment by MasterCarl** [comment]
Maybe this is some kind of race condition with the JavaScript actions not being executed in time. Didn't you have this issue before, @tom95 ?

**Comment by tom95** [comment]
@Blaidd-Drwg once you merged with dev I would hope that it should always succeed. The test had a bug I didn't notice until then.

I think the reason why it sometimes failed and sometimes not is because of the factory girl build_list calls, which seemed to randomly append suffixes to instance data so that they are different. Sometimes the order of the profile names and ages happened to result in the same order, which was what the buggy test required.

**Comment by Blaidd-Drwg** [comment]
Hmm, the current dev still fails locally on both my machines though. Could you please try something out for me? Could you checkout the branch `374_DebugSortTest`, run `rspec | grep Karl` and post the results?
My results are:
```html
<li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Karl97 Doe97 <b class="caret"></b></a><ul class="dropdown-menu">
      <td>Karl98 Doe98</td>
      <td>Karl99 Doe99</td>
      <td>Karl100 Doe100</td>
      <td>Karl101 Doe101</td>
      <td>Karl102 Doe102</td>
```
Which means the test **should** actually fail, because the names are not sorted alphabetically.

**Comment by Blaidd-Drwg** [comment]
Turns out @MasterCarl was right, if I add `sleep(1)` before printing the HTML, the names are sorted correctly.
@tom95, do you know if there's a cleaner way to fix this?

**Comment by tom95** [comment]
It's pretty hard, in particular if we're dealing with a reload (aka a case where the same page is displayed). What one does is asserting for the existence of some element unqiue to the page you're expecting to be displayed right now, since capybara will retry finding this element until a timeout is reached. I (hopefully) fixed this for good as part of this PR https://github.com/hpi-swt2/workshop-portal/pull/405/files where I check for the class change on the little arrow used for sorting. I will close this issue when the PR gets merged, but please reopen it if at any point that test is making trouble again.

**Comment by phnm** [comment]
I might have a similar issue with another feature test that only fails on Travis, but always succeeds in local environments, even tried different machines. At least it fails consistently on Travis, but it's also a sorting issue. I already tried it with sleep(1) with no success. Here is a build with a debug print of the page.body and the names array with the expected order, which for some reason, just won't match:
https://travis-ci.org/hpi-swt2/workshop-portal/builds/195176918
The weird thing is that this test already passed on Travis at some point, since I forked it from dev. I haven't touched the test or the feature it tests though, since it's supposed to be unrelated to my story... I just added a new field to the ApplicationLetter model.

**Comment by Blaidd-Drwg** [comment]
@tom95 Well, I ran my tests on your branch a few times and the test never failed, so it looks like you fixed it. A big thumbs up for that! I'll test a little more thoroughly tomorrow to make sure this bug is definitely squashed.
We should also consider randomizing the names created by the Profile factory. No point in testing the sorting if the order by name is identical to the order by id. Though I suspect that doing that would uncover a lot more cases like this one...

**Comment by Blaidd-Drwg** [comment]
Fixed by #405
